// Code generated by images. DO NOT EDIT.

package images

import (
	"github.com/charliego3/assistant/utility"
	_ "embed"

	"github.com/progrium/macdriver/macos/appkit"
)

var (
	//go:embed mongo.svg
	MongoData []byte

	//go:embed mysql.svg
	MysqlData []byte

	//go:embed postgresql.svg
	PostgresqlData []byte

	//go:embed redis.svg
	RedisData []byte
)

func Mongo() appkit.Image {
	return appkit.NewImageWithData(MongoData)
}

func MongoView() appkit.ImageView {
	return appkit.ImageView_ImageViewWithImage(Mongo())
}

func Mysql() appkit.Image {
	return appkit.NewImageWithData(MysqlData)
}

func MysqlView() appkit.ImageView {
	return appkit.ImageView_ImageViewWithImage(Mysql())
}

func Postgresql() appkit.Image {
	image :=  appkit.NewImageWithData(PostgresqlData)
	image.SetSize(utility.SizeOf(50, 50))
	return image
}

func PostgresqlView() appkit.ImageView {
	return appkit.ImageView_ImageViewWithImage(Postgresql())
}

func Redis() appkit.Image {
	return appkit.NewImageWithData(RedisData)
}

func RedisView() appkit.ImageView {
	return appkit.ImageView_ImageViewWithImage(Redis())
}
